### ISSUE TITLE
garbled problem

### ISSUE THREAD

**Issue by aihk** [the-via/app#48] opened 2022-08-29 12:18 UTC
When the labels attribute in the .json file has Chinese characters, there will be garbled characters. Can you fix this problem?

**Comment by olivia** [comment] 2022-10-29 01:37
Would you mind providing a sample `.json` file to replicate with?

**Comment by olivia** [comment] 2022-11-08 05:45
Closing due to bug not being reproducible.

**Closed** 2022-11-08 05:46 UTC

**Comment by aihk** [comment] 2022-12-21 03:07
> Would you mind providing a sample `.json` file to replicate with?
Sorry ~ I saw the news today. How can I provide you .json
